let langs = [
    { code: 'BG', language: 'Bulgarian'},
    { code: 'CS', language: 'Czech'},
    { code: 'DA', language: 'Danish'},
    { code: 'DE', language:  'German'},
    { code: 'EL', language:  'Greek'},
    { code: 'EN', language:  'English'},
    { code: 'ES', language:  'Spanish'},
    { code: 'ET', language:  'Estonian'},
    { code: 'FI', language:  'Finnish'},
    { code: 'FR', language:  'French'},
    { code: 'HU', language:  'Hungarian'},
    { code: 'ID', language:  'Indonesian'},
    { code: 'IT', language:  'Italian'},
    { code: 'JA', language:  'Japanese'},
    { code: 'KO', language:  'Korean'},
    { code: 'LT', language:  'Lithuanian'},
    { code: 'LV', language:  'Latvian'},
    { code: 'NB', language:  'Norwegian'},
    { code: 'NL', language:  'Dutch'},
    { code: 'PL', language:  'Polish'},
    { code: 'PT', language:  'Portuguese'},
    { code: 'RO', language:  'Romanian'},
    { code: 'RU', language:  'Russian'},
    { code: 'SK', language:  'Slovak'},
    { code: 'SL', language:  'Slovenian'},
    { code: 'SV', language:  'Swedish'},
    { code: 'TR', language:  'Turkish'},
    { code: 'UK', language:  'Ukrainian'},
    { code: 'ZH', language:  'Chinese'},
]

module.exports = langs;

